//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PET
    {
        public int Id { get; set; }
        public string Categorie { get; set; }
        public string Rasa { get; set; }
        public double Pret { get; set; }
        public int AnPrimire { get; set; }
    }
}
